# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hello/Num.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Num(genpy.Message):
  _md5sum = "47f709c3ebbeb15e51c9821690dd7abd"
  _type = "hello/Num"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String first_name
geometry_msgs/Vector3 coordinate
int64 num

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['first_name','coordinate','num']
  _slot_types = ['std_msgs/String','geometry_msgs/Vector3','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       first_name,coordinate,num

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Num, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.first_name is None:
        self.first_name = std_msgs.msg.String()
      if self.coordinate is None:
        self.coordinate = geometry_msgs.msg.Vector3()
      if self.num is None:
        self.num = 0
    else:
      self.first_name = std_msgs.msg.String()
      self.coordinate = geometry_msgs.msg.Vector3()
      self.num = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.first_name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3dq().pack(_x.coordinate.x, _x.coordinate.y, _x.coordinate.z, _x.num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.first_name is None:
        self.first_name = std_msgs.msg.String()
      if self.coordinate is None:
        self.coordinate = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.first_name.data = str[start:end].decode('utf-8')
      else:
        self.first_name.data = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.coordinate.x, _x.coordinate.y, _x.coordinate.z, _x.num,) = _get_struct_3dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.first_name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3dq().pack(_x.coordinate.x, _x.coordinate.y, _x.coordinate.z, _x.num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.first_name is None:
        self.first_name = std_msgs.msg.String()
      if self.coordinate is None:
        self.coordinate = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.first_name.data = str[start:end].decode('utf-8')
      else:
        self.first_name.data = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.coordinate.x, _x.coordinate.y, _x.coordinate.z, _x.num,) = _get_struct_3dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3dq = None
def _get_struct_3dq():
    global _struct_3dq
    if _struct_3dq is None:
        _struct_3dq = struct.Struct("<3dq")
    return _struct_3dq
